#!/usr/bin/env python

import boto3 as boto
import json

STAGE = 'staging'
REGION = 'eu-central-1'
PROJECT = 'santander'

client = boto.client('ec2', region_name=REGION)

instances = client.describe_instances()

groups = {}

for reservation in instances['Reservations']:
    for instance in reservation['Instances']:
        if not instance.get("Tags"):
            continue
        if not instance['State']['Name'] == "running":
            continue
        tags = dict(map((lambda x: [x['Key'],x['Value']]),instance['Tags']))
        if tags.get("Project") != PROJECT:
            continue                  
        if tags.get("Stages") != STAGE:
            continue
        if tags.get("Roles"):
            for group in tags.get("Roles").split(','):
                if not groups.get(group):
                    groups[group] = []
                groups[group].append(instance['PublicIpAddress'])

print json.dumps(groups,indent=2)
