---
- name: ANSISTRANO | GCE_GIT | Delete destination repo
  file: name={{ ansistrano_deploy_to }}/repo state=absent

- name: ANSISTRANO | GCE_GIT | Update remote repository
  command: gcloud source repos clone {{ ansistrano_gce_git_repo }} {{ ansistrano_deploy_to }}/repo
  #  git:
  #  repo: "{{ ansistrano_git_repo }}"
  #  dest: "{{ ansistrano_deploy_to }}/repo"
  #  version: "{{ ansistrano_git_branch }}"
  #  accept_hostkey: true
  #  update: yes
  #  force: yes
  register: ansistrano_git_result_update
  when: ansistrano_git_identity_key_path|trim == ''

- name: ANSISTRANO | GCE_GIT | Register ansistrano_git_result variable
  set_fact: ansistrano_git_result={{ ansistrano_git_result_update_ssh if ansistrano_git_result_update|skipped else ansistrano_git_result_update }}

- name: ANSISTRANO | GCE_GIT | Set git_real_repo_tree
  set_fact:
    ansistrano_git_real_repo_tree: "{{ ansistrano_git_repo_tree | trim | regex_replace('^[/]*', '') | regex_replace('[/]*$', '') }}"

- name: ANSISTRANO | GCE_GIT | Create release folder
  file:
    state: directory
    path: "{{ ansistrano_release_path.stdout }}"

- name: ANSISTRANO | GCE_GIT | Sync repo subtree["{{ ansistrano_git_real_repo_tree }}"] to release path
  shell: >-
           {
             git ls-files --with-tree="{{ ansistrano_git_branch }}";
             git submodule foreach --recursive --quiet 'git ls-files --with-tree="$sha1" | sed "s#^#$path/#"';
           }
           | grep "^$prefix"
           | sed "s#^$prefix/##"
           | rsync -a --files-from=- "./$prefix/" {{ ansistrano_release_path.stdout }}/
  args:
    chdir: "{{ ansistrano_deploy_to }}/repo/"
  environment:
    prefix: "{{ ansistrano_git_real_repo_tree }}"
