- name: Clear cache
  command: php bin/console cache:clear --env={{shortcut_stages}} --no-debug --no-interaction
  args:
    chdir: "{{ ansistrano_deploy_to }}/current"
  run_once: true  

- name: Get Enqueue processes
  shell: "ps -ef | grep -v grep | grep -w php | grep enqueue | awk '{print $2}'"
  register: running_processes

- name: Kill Enqueue processes
  shell: "kill -9 {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"